USE V9nEW

TRUNCATE TABLE HARDWARE_REGISTER
TRUNCATE TABLE GROUP_MASTER
TRUNCATE TABLE SUBGROUP_MASTER
TRUNCATE TABLE LOCATION_MASTER

TRUNCATE TABLE LOCATION_MASTER

TRUNCATE TABLE SUBLOCATION_MASTER

SELECT * FROM hardware_register

--TRUNCATE TABLE HARDWARE_REGISTER
--TRUNCATE TABLE HARDWARE_REGISTER
--TRUNCATE TABLE HARDWARE_REGISTER
--TRUNCATE TABLE HARDWARE_REGISTER
--TRUNCATE TABLE HARDWARE_REGISTER